version: 2
updates:
  - package-ecosystem: "uv"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch" # we don't want to be bothered with patch updates for anything except security updates
      - dependency-name: "boto3" # boto3 gets patch updates way too frequently and they're usually not important
        update-types:
          - "version-update:semver-patch"
      - dependency-name: "sphinx*" # read-the-docs uses specific versions of sphinx, so we generally want to stay tightly pinned unless there's a major version change
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      # ignore production dependencies except for major updates, to ensure maximum compatibility with users of this library. As of 2025-07-21 there doesn't appear to be a way to specify these with a setting instead of enumerating them individually
      - dependency-name: "pydantic"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      - dependency-name: "inflection"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      - dependency-name: "lxml"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

    groups:
      prod-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
