# Changes here will be overwritten by Copier
_commit: 167d98b
_src_path: gh:LabAutomationAndScreening/copier-python-package-template.git
description: Generating programs for ViaLab to control an Integra Assist Plus liquid
    handling robot
full_repo_url: https://github.com/LabAutomationAndScreening/pyalab
package_name: pyalab
primary_author: Eli Fine
python_ci_versions:
- 3.12.8
- 3.13.1
python_version: 3.12.8
repo_name: pyalab
ssh_port_number: 56475

