name: Publish to Package Registry

on:
  workflow_dispatch:
    inputs:
      publish_to_primary:
        description: 'Publish to Primary Registry'
        type: boolean
        required: false
        default: false
env:
  PYTHONUNBUFFERED: True
  PRE_COMMIT_HOME: ${{ github.workspace }}/.precommit_cache

permissions:
  id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)
  contents: read # need to explicitly provide this whenever defining permissions because the default value is 'none' for anything not explicitly set when permissions are defined

jobs:
  get-values:
    name: Get Values
    runs-on: ubuntu-24.04
    outputs:
      package-version: ${{ steps.extract-package-version.outputs.package_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.12.7
      - name: Extract package version
        id: extract-package-version
        run: |
          VERSION=$(python3 ./.github/workflows/git_tag.py)
          echo "Extracted version: $VERSION"
          echo "package_version=$VERSION" >> $GITHUB_OUTPUT

  lint:
    name: Pre-commit
    uses: ./.github/workflows/pre-commit.yaml
    permissions:
      contents: write # needed for mutex
      id-token: write # needed to assume OIDC roles (e.g. for downloading from CodeArtifact)
    with:
      python-version: 3.12.7

  test:
    needs: [ lint ]
    strategy:
      matrix:
        os:
          - "ubuntu-24.04"
          - windows-2025
        python-version:

          - 3.12.7

          - 3.13.2

        include:
          - os: "ubuntu-24.04"
            python-version: "3.12.7"
            JOB_MATCHING_DEV_ENV: true

    runs-on: ${{ matrix.os }}
    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Install python tooling
        uses: ./.github/actions/install_deps
        with:
          python-version: ${{ matrix.python-version }}

      - name: Unit test
        run: uv run pytest --durations=5

  build:
    needs: [ test ]
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Install python tooling
        uses: ./.github/actions/install_deps
        with:
          python-version: 3.12.7


      - name: Build package
        run: |

          uv build --no-sources

      - name: Upload build package
        uses: actions/upload-artifact@v4.6.2
        with:
          name: python-package-distributions
          path: dist/
          if-no-files-found: error


  publish-to-staging:
    name: Publish Python distribution to Staging Package Registry
    needs: [ build ]
    runs-on: ubuntu-24.04
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pyalab
    permissions:
      attestations: write
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v5.0.0
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          attestations: false
          repository-url: https://test.pypi.org/legacy/



  install-from-staging:
    name: Install package from staging registry
    needs: [ publish-to-staging, get-values ]
    strategy:
      matrix:
        os:
          - "ubuntu-24.04"
          - windows-2025
        python-version:

          - 3.12.7

          - 3.13.2

        include:
          - os: "ubuntu-24.04"
            python-version: "3.12.7"
            JOB_MATCHING_DEV_ENV: true

    runs-on: ${{ matrix.os }}
    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Wait for Test PyPI to serve the new version
        shell: bash
        run: |
          set -euo pipefail
          PKG="pyalab"
          VER="${{ needs.get-values.outputs.package-version }}"
          for i in $(seq 1 60); do
            code="$(curl -fsS -o /dev/null -w '%{http_code}' "https://test.pypi.org/pypi/${PKG}/${VER}/json" || true)"
            if [ "$code" = "200" ]; then
              echo "Found ${PKG}==${VER} on Test PyPI."
              break
            fi
            echo "Not yet available; sleeping 5s..."
            sleep 5
          done

          if [ "$code" != "200" ]; then
            echo "Timeout waiting for ${PKG}==${VER} on Test PyPI API."
            exit 1
          fi

          # Then try to install with retries to ensure it's actually available in the index
          for i in $(seq 1 12); do
            if pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://www.pypi.org/simple "${PKG}==${VER}" --no-cache-dir --quiet; then
              echo "Successfully installed ${PKG}==${VER}!"
              exit 0
            fi
            echo "Package not yet installable; sleeping 10s... (attempt $i/12)"
            sleep 10
          done

          echo "Timeout waiting for ${PKG}==${VER} to be installable."
          exit 1
      - name: Display dependencies
        run: pip list
      - name: Confirm library can be imported successfully
        env:
          PYTHONPATH: ""  # avoid picking up local sources
        shell: bash
        run: |
          python - <<'PY'
          import sys, importlib, importlib.util, importlib.metadata as md, pathlib
          print(f"Python version {sys.version}")
          mod_name = "pyalab"
          dist_name = mod_name
          m = importlib.import_module(mod_name)
          spec = importlib.util.find_spec(mod_name)
          origin = (getattr(spec, "origin", None) or getattr(m, "__file__", "")) or ""
          p = pathlib.Path(origin)
          print(f"Imported from: {p}")
          assert any(s in str(p) for s in ("site-packages", "dist-packages")), f"Expected site/dist-packages, got {p}"
          expected = "${{ needs.get-values.outputs.package-version }}"
          installed = md.version(dist_name)
          print(f"Installed distribution version: {installed} (expected {expected})")
          assert installed == expected, f"Version mismatch: expected {expected}, got {installed}"
          PY

  create-tag:
    name: Create the git tag
    if: ${{ fromJSON(github.event.inputs.publish_to_primary) }}
    needs: [ install-from-staging ]
    permissions:
      contents: write # needed to push the tag
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.12.7
      - name: Confirm tag not already present
        run: python3 ./.github/workflows/git_tag.py --confirm-tag-not-present
      - name: Create tag
        run: python3 ./.github/workflows/git_tag.py --push-tag-to-remote

  publish-to-primary:
    name: Publish Python distribution to Primary Package Registry
    if: ${{ fromJSON(github.event.inputs.publish_to_primary) }}
    needs: [ create-tag ]
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      url: https://pypi.org/p/pyalab
    permissions:
      attestations: write
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v5.0.0
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          attestations: false

  install-from-primary:
    name: Install package from primary registry
    if: ${{ fromJSON(github.event.inputs.publish_to_primary) }}
    needs: [ publish-to-primary, get-values ]
    strategy:
      matrix:
        os:
          - "ubuntu-24.04"
          - windows-2025
        python-version:

          - 3.12.7

          - 3.13.2

        include:
          - os: "ubuntu-24.04"
            python-version: "3.12.7"
            JOB_MATCHING_DEV_ENV: true

    runs-on: ${{ matrix.os }}
    env:
      UV_PYTHON: ${{ matrix.python-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
      - name: Setup python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Wait for PyPI to serve the new version
        shell: bash
        run: |
          set -euo pipefail
          PKG="pyalab"
          VER="${{ needs.get-values.outputs.package-version }}"
          for i in $(seq 1 60); do
            code="$(curl -fsS -o /dev/null -w '%{http_code}' "https://pypi.org/pypi/${PKG}/${VER}/json" || true)"
            if [ "$code" = "200" ]; then
              echo "Found ${PKG}==${VER} on PyPI."
              break
            fi
            echo "Not yet available; sleeping 5s..."
            sleep 5
          done

          if [ "$code" != "200" ]; then
            echo "Timeout waiting for ${PKG}==${VER} on PyPI API."
            exit 1
          fi

          # Then try to install with retries to ensure it's actually available in the index
          for i in $(seq 1 12); do
            if pip install --index-url https://pypi.org/simple/ "${PKG}==${VER}" --no-cache-dir --quiet; then
              echo "Successfully installed ${PKG}==${VER}!"
              exit 0
            fi
            echo "Package not yet installable; sleeping 10s... (attempt $i/12)"
            sleep 10
          done

          echo "Timeout waiting for ${PKG}==${VER} to be installable."
          exit 1
      - name: Display dependencies
        run: pip list
      - name: Confirm library can be imported successfully
        env:
          PYTHONPATH: ""  # avoid picking up local sources
        shell: bash
        run: |
          python - <<'PY'
          import sys, importlib, importlib.util, importlib.metadata as md, pathlib
          print(f"Python version {sys.version}")
          mod_name = "pyalab"
          dist_name = mod_name
          m = importlib.import_module(mod_name)
          spec = importlib.util.find_spec(mod_name)
          origin = (getattr(spec, "origin", None) or getattr(m, "__file__", "")) or ""
          p = pathlib.Path(origin)
          print(f"Imported from: {p}")
          assert any(s in str(p) for s in ("site-packages", "dist-packages")), f"Expected site/dist-packages, got {p}"
          expected = "${{ needs.get-values.outputs.package-version }}"
          installed = md.version(dist_name)
          print(f"Installed distribution version: {installed} (expected {expected})")
          assert installed == expected, f"Version mismatch: expected {expected}, got {installed}"
          PY
